services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      # IMPORTANTE: Solo escuchamos en 127.0.0.1 (localhost)
      # Esto obliga a que todo el tráfico pase por Nginx (puertos 8883 o 443)
      # Nadie podrá conectarse directamente desde internet saltándose la seguridad.
      - "127.0.0.1:1883:1883"
      - "127.0.0.1:9001:9001"
    volumes:
      # IMPORTANTE: Mapeamos carpetas completas, NO archivos individuales.
      # Esto evita el error de montaje y permite que las contraseñas se guarden.
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
